### ISSUE TITLE
Trying to render subsequent lists using listItem will render the contents of the first section in every following section

### ISSUE THREAD

**Issue by draoncc** [pattern-lab/patternengine-node-mustache#11] opened 2017-05-23 08:52 UTC
I am using Pattern Lab Node `v2.9.3` on `Linux`, using the `gulp` configuration.

##### Expected Behavior
```
Foo:
{{#listItems.one}}foo{{/listItems.one}}
Bar:
{{#listItems.one}}bar{{/listItems.one}}
```
should render to
```
Foo:
foo
Bar:
bar
```

##### Actual Behavior
```
Foo:
{{#listItems.one}}foo{{/listItems.one}}
Bar:
{{#listItems.one}}bar{{/listItems.one}}
```
actually renders to
```
Foo:
foo
Bar:
foo
```

##### Steps to Reproduce
1. Install fresh `edition-node-gulp`.
2. Add a new pattern with the above code.
3. Run `gulp patternlab:build` and inspect the rendered HTML in `/public/patterns/xxx/xxx.markup-only.html`.

##### Additional Notes
```
{{#listItems.one}}foo{{/listItems.one}}
{{#listItems.two}}bar{{/listItems.two}}
```
renders as expected.

I don't have the time to test more cases right now.
Also hope this is an issue with the mustache patternengine, not that I post it to the wrong place.

**Comment by bmuenzenmeyer** [comment] 2017-05-23 12:04
@draoncc thanks for the report - this is a fine place to report an issue and I appreciate the reduced example.

I think your report is a duplicate of https://github.com/pattern-lab/patternlab-node/issues/553 on the core library, which is likely where this will be fixed. I'll tag this as a duplicate and make sure to cross link this - and consider it a +1 to fix that

thanks again!

**Closed as completed** 2017-05-23 12:04 UTC
Labels: duplicate
